name: Task Status Check
run-name: Task status check
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.list_tasks_output.outputs.
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Lokalise CLI
      run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
    - name: List Tasks
      id: list_tasks_output
      env: 
        VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
        VAR_LOKALISE_PROJECT_ID: ${{ vars.PROJECT_ID }}
      run: echo "::set-output name=task_list::./bin/lokalise2 task list --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }}"
